project_name: gist
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
  - main: .
    binary: gist
    ldflags:
      - -s -w
      - -X github.com/b4b4r07/gist/cmd.Version={{.Version}}
      - -X github.com/b4b4r07/gist/cmd.BuildSHA={{.ShortCommit}}
      - -X github.com/b4b4r07/gist/cmd.BuildTag={{.Tag}}
    env:
      - CGO_ENABLED=0
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      darwin: darwin
      linux: linux
      windows: windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
release:
  prerelease: auto

# https://goreleaser.com/customization/#Homebrew
brews:
- tap:
    owner: b4b4r07
    name: homebrew-tap
    token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
  folder: Formula
  commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
  homepage: https://babarot.me/gist
  description: |
    A simple gist editor for CLI
  license: MIT
  skip_upload: auto
  test: |
    system "#{bin}/gist", "--version"
